export const europeanCountries = [
  { code: 'IT', name: 'Italia', nameEn: 'Italy' },
  { code: 'ES', name: 'Spagna', nameEn: 'Spain' },
  { code: 'PT', name: 'Portogallo', nameEn: 'Portugal' },
  { code: 'FR', name: 'Francia', nameEn: 'France' },
  { code: 'DE', name: 'Germania', nameEn: 'Germany' },
  { code: 'RU', name: 'Russia', nameEn: 'Russia' },
  { code: 'GB', name: 'Regno Unito', nameEn: 'United Kingdom' },
  { code: 'IE', name: 'Irlanda', nameEn: 'Ireland' },
  { code: 'NL', name: 'Paesi Bassi', nameEn: 'Netherlands' },
  { code: 'BE', name: 'Belgio', nameEn: 'Belgium' },
  { code: 'LU', name: 'Lussemburgo', nameEn: 'Luxembourg' },
  { code: 'AT', name: 'Austria', nameEn: 'Austria' },
  { code: 'CH', name: 'Svizzera', nameEn: 'Switzerland' },
  { code: 'GR', name: 'Grecia', nameEn: 'Greece' },
  { code: 'PL', name: 'Polonia', nameEn: 'Poland' },
  { code: 'CZ', name: 'Repubblica Ceca', nameEn: 'Czech Republic' },
  { code: 'SK', name: 'Slovacchia', nameEn: 'Slovakia' },
  { code: 'HU', name: 'Ungheria', nameEn: 'Hungary' },
  { code: 'RO', name: 'Romania', nameEn: 'Romania' },
  { code: 'BG', name: 'Bulgaria', nameEn: 'Bulgaria' },
  { code: 'HR', name: 'Croazia', nameEn: 'Croatia' },
  { code: 'SI', name: 'Slovenia', nameEn: 'Slovenia' },
  { code: 'EE', name: 'Estonia', nameEn: 'Estonia' },
  { code: 'LV', name: 'Lettonia', nameEn: 'Latvia' },
  { code: 'LT', name: 'Lituania', nameEn: 'Lithuania' },
  { code: 'FI', name: 'Finlandia', nameEn: 'Finland' },
  { code: 'SE', name: 'Svezia', nameEn: 'Sweden' },
  { code: 'DK', name: 'Danimarca', nameEn: 'Denmark' },
  { code: 'NO', name: 'Norvegia', nameEn: 'Norway' },
  { code: 'IS', name: 'Islanda', nameEn: 'Iceland' },
  { code: 'MT', name: 'Malta', nameEn: 'Malta' },
  { code: 'CY', name: 'Cipro', nameEn: 'Cyprus' },
  { code: 'UA', name: 'Ucraina', nameEn: 'Ukraine' },
  { code: 'BY', name: 'Bielorussia', nameEn: 'Belarus' },
  { code: 'MD', name: 'Moldavia', nameEn: 'Moldova' },
  { code: 'RS', name: 'Serbia', nameEn: 'Serbia' },
  { code: 'BA', name: 'Bosnia ed Erzegovina', nameEn: 'Bosnia and Herzegovina' },
  { code: 'ME', name: 'Montenegro', nameEn: 'Montenegro' },
  { code: 'AL', name: 'Albania', nameEn: 'Albania' },
  { code: 'MK', name: 'Macedonia del Nord', nameEn: 'North Macedonia' },
  { code: 'XK', name: 'Kosovo', nameEn: 'Kosovo' },
  { code: 'AD', name: 'Andorra', nameEn: 'Andorra' },
  { code: 'MC', name: 'Monaco', nameEn: 'Monaco' },
  { code: 'SM', name: 'San Marino', nameEn: 'San Marino' },
  { code: 'VA', name: 'Città del Vaticano', nameEn: 'Vatican City' },
  { code: 'LI', name: 'Liechtenstein', nameEn: 'Liechtenstein' },
] as const

export type CountryCode = typeof europeanCountries[number]['code']